avalanche_imagine:
    filters:
        thumbnail:
            type:    thumbnail
            options: { size: [200, 120], mode: outbound, quality: 100, format: png } 
        producto_detalle:
            type:    thumbnail
            options: { size: [400, 300], mode: outbound, quality: 100, format: png } 
        producto_slider:
            type:    thumbnail
            options: { size: [550, 400], mode: outbound, quality: 100, format: png } 
        banner:
            type:    thumbnail
            options: { size: [800, 220], mode: outbound, quality: 100, format: png }