# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512




    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
            anonymous:          true




        main:
            pattern:             .*

            oauth:
                resource_owners:
                    facebook:      /secured/login_facebook
                login_path:        /secured/login
                # failure_path:      /login_app
                failure_path:      /secured/login
                # oauth_user_provider:
                #     service: hwi_oauth.user.provider.entity
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
                # oauth_user_provider:
                #     service: my.oauth_aware.user_provider.service


            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   /login_app
            logout:             true
            anonymous:          true

   

    # access_control:
    #     - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/tienda.creacion, role: ROLE_USER }
#        - { path: ^/admin/, role: ROLE_ADMIN }