# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
                login_path: /usuario.ingreso
                check_path: /usuario.check
                default_target_path: /index.do
                remember_me: true
#            logout:       true
            logout:
                path:   /salir
                target: /index.do
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tienda.creacion, role: ROLE_USER }
#        - { path: ^/admin/, role: ROLE_ADMIN }