parameters:
#    selnet_tienda_online.example.class: Selnet\TiendaOnlineBundle\Example
    app_notificaciones.notificacion.class: Selnet\TiendaOnlineBundle\Servicio\NotificacionService

 

services:
    tienda_user.registration.form.type:
        class: Selnet\TiendaOnlineBundle\Form\UsuarioType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: selnet_tiendaonlinebundle_usuariotype }



    app_notificaciones.notificacion.manager:
        class: %app_notificaciones.notificacion.class%
        arguments: [@doctrine.orm.entity_manager   ]
