parameters:
#    selnet_tienda_online.example.class: Selnet\TiendaOnlineBundle\Example
    artsenal.notificacion.class: Selnet\TiendaOnlineBundle\Servicio\NotificacionService
    artsenal.cart.class:         Selnet\TiendaOnlineBundle\Servicio\CartService

 

services:
    tienda_user.registration.form.type:
        class: Selnet\TiendaOnlineBundle\Form\UsuarioType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: selnet_tiendaonlinebundle_usuariotype }



    app_notificaciones.notificacion.manager:
        class: %artsenal.notificacion.class%
        arguments: [@doctrine.orm.entity_manager   ]


    artsenal.cart.manager:
        class: %artsenal.cart.class%
        arguments: [@doctrine.orm.entity_manager , @session  ]
