services:
  sonata.admin.categoria:
    class: Setnet\ArtsenalBundle\Admin\CategoriaAdmin
    arguments: [null, Setnet\ArtsenalBundle\Entity\ArtCategoria, 'SonataAdminBundle:CRUD']
    calls:
        - [setTranslationDomain, [SetnetAdminBundle]]
    tags:
        - { name: sonata.admin, manager_type: orm, group: Categoria, label: Categorias }

  sonata.admin.subcategoria:
    class: Setnet\ArtsenalBundle\Admin\SubcategoriaAdmin
    arguments: [null, Setnet\ArtsenalBundle\Entity\ArtSubcategoria, 'SonataAdminBundle:CRUD']
    calls:
        - [setTranslationDomain, [SetnetAdminBundle]]
    tags:
        - { name: sonata.admin, manager_type: orm, group: Categoria, label: Subcategoria }



  sonata.admin.slider:
    class: Setnet\ArtsenalBundle\Admin\BannerAdmin
    arguments: [null, Setnet\ArtsenalBundle\Entity\CmsSlider, 'SonataAdminBundle:CRUD']
    calls:
        - [setTranslationDomain, [SetnetAdminBundle]]
    tags:
        - { name: sonata.admin, manager_type: orm, group: Sitio, label: Slider }
        
        


  sonata.admin.contenido:
    class: Setnet\ArtsenalBundle\Admin\ContenidoAdmin
    arguments: [null, Setnet\ArtsenalBundle\Entity\Contenido, 'SonataAdminBundle:CRUD']
    calls:
        - [setTranslationDomain, [SetnetAdminBundle]]
    tags:
        - { name: sonata.admin, manager_type: orm, group: Sitio, label: Contenido }
        
        
        
        
  sonata.admin.usuario:
    class: Setnet\ArtsenalBundle\Admin\UsuarioAdmin
    arguments: [null, Setnet\ArtsenalBundle\Entity\ArtUsuario, 'SonataAdminBundle:CRUD']
    calls:
        - [setTranslationDomain, [SetnetAdminBundle]]
    tags:
        - { name: sonata.admin, manager_type: orm, group: Usuario, label: Usuario }
        
        
  sonata.admin.rol:
    class: Setnet\ArtsenalBundle\Admin\RolAdmin
    arguments: [null, Setnet\ArtsenalBundle\Entity\ArtRol, 'SonataAdminBundle:CRUD']
    calls:
        - [setTranslationDomain, [SetnetAdminBundle]]
    tags:
        - { name: sonata.admin, manager_type: orm, group: Seguridad, label: Roles}
        
        
 