
home:
    pattern:  /artsenal_home
    defaults: { _controller: SetnetArtsenalBundle:Default:index }
    


categoria_producto:
  pattern:  /categoria/{categoria}
  defaults: { _controller: SetnetArtsenalBundle:Default:categoria }



#menu 
registrar_usuario:
    pattern:  /registrar
    defaults: { _controller: SetnetArtsenalBundle:Usuario:updateUsuario }    
    
    
mostrar_carrito:
  pattern:  /checkout
  defaults: { _controller: SetnetArtsenalBundle:Cart:checkout}
  
detalle_producto:
    pattern:  /detalleProducto/{id_producto}
    defaults: { _controller: SetnetArtsenalBundle:Default:productosDetalle }

ver_tienda:
    pattern:  /tienda/{id_tienda}
    defaults: { _controller: SetnetArtsenalBundle:Tienda:verTienda }


#
#### informacion de la pagina
artsenal_quienes_somos:
    pattern:  /about
    defaults: { _controller: SetnetArtsenalBundle:Default:quienesSomos }
#
artsenal_preguntas:
    pattern:  /preguntas
    defaults: { _controller: SetnetArtsenalBundle:Default:preguntas }
#
artsenal_politicas_privacidad:
    pattern:  /politicas_privacidad
    defaults: { _controller: SetnetArtsenalBundle:Default:politicasPrivacidad }
#  
#
#
#

#
#
# 
#setnet_artsenal_vendedor:
#    pattern:  /creacion
#    defaults: { _controller: SetnetArtsenalBundle:Default:creacionTienda }
#
# 
#
#setnet_artsenal_nuevo_producto:
#    pattern:  /creacionProductoTemporal
#    defaults: { _controller: SetnetArtsenalBundle:Default:creacionProductoTemporal }
#
#setnet_artsenal_nuevo_imagen:
#    pattern:  /creacionImagenTemporal
#    defaults: { _controller: SetnetArtsenalBundle:Default:creacionImagenTemporal }
#
#vendedor:
#    pattern:  /vendedor
#    defaults: { _controller: SetnetArtsenalBundle:Default:vendedor }
#
#
#
#
#
#perfil:
#    pattern:  /perfil
#    defaults: { _controller: SetnetArtsenalBundle:Perfil:perfil }
#
#
#

#    
#
#
#registrar_message:
#    pattern:  /registroResultado
#    defaults: { _controller: SetnetArtsenalBundle:Default:registraResultadoVendedor }
#
#
#
#
#post_login:
#    pattern:  /Home
#    defaults: { _controller: SetnetArtsenalBundle:Default:registraResultadoVendedor }
#    
#        
#log_out:
#    pattern:  /logout
#    defaults: { _controller: SetnetArtsenalBundle:Usuario:logout }
#    
#    
#    
#  
#registrar:
#    pattern:  /registrar
#    defaults: { _controller: SetnetArtsenalBundle:Usuario:updateUsuario }    
#  
#  
#  
#registrar_fb:
#    pattern:  /facebook_log
#    defaults: { _controller: SetnetArtsenalBundle:Usuario:updateUsuarioFb }    
#    
#    
#    
#configuracion:
#    pattern:  /configuracion
#    defaults: { _controller: SetnetArtsenalBundle:Usuario:configura }
#  
#  
#### CREACION DE PRODUCTO
#
#    
#crear_editar_producto:
#    pattern:  /producto/new 
#    defaults: { _controller: SetnetArtsenalBundle:Producto:productoNew}
#    
#    
#editar_producto:
#    pattern:  /producto/edit/{id_producto} 
#    defaults: { _controller: SetnetArtsenalBundle:Producto:productoEdit}
#
#  
#
#### CREACION DE TIENDA
#
#crear_tienda:
#    pattern:  /crear
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:crear }
#
#
#listar_articulos:
#    pattern:  /articulos
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:mostrarArticulos }
#
#crear_articulo_nuevo:
#    pattern:  /articulos_nuevo/
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:crearArticulosNuevo }
#
#mostrar_articulo:
#    pattern:  /articulos/{id_articulo}
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:editarArticulos }
#
#
#crear_facturacion:
#    pattern:  /facturacion
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:crearFacturacion }
#
#crear_finalizar:
#    pattern:  /finalizar
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:crearFinalizar }
#
#
#upload_imagen_producto:
#    pattern:  /uploadImage
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:uploadImage }
#
#
#politicas:
#    pattern:  /politicas
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:politicas }
#
#ver_politicas:
#    pattern:  /politicas/{id_tienda}
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:verPoliticas }
#
#
#informacion:
#    pattern:  /informacion
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:informacion }
#
#tienda_preview:
#    pattern:  /preview
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:preview }
#
#mi_tienda:
#    pattern:  /tienda
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:miTienda }
#

#
###### mensajeria 
#
#tienda_mensajes:
#    pattern:  /mensajes
#    defaults: { _controller: SetnetArtsenalBundle:Mensajes:index }
#
#tienda_mensajes_nuevo:
#    pattern:  /mensajes/new
#    defaults: { _controller: SetnetArtsenalBundle:Mensajes:nuevo }
#
#
#suscripciones:
#    pattern:  /suscripcion
#    defaults: { _controller: SetnetArtsenalBundle:Usuario:suscripcion }
#
#
#ver_productos_tienda:
#    pattern:  /ver_articulos/{subcategoria}/{tienda}
#    defaults: { _controller: SetnetArtsenalBundle:Tienda:mostrarProductosTienda }
#
#
#
##### cart 
#
#
#agregar_item:
#    pattern:  /addCart/{id_producto}
#    defaults: { _controller: SetnetArtsenalBundle:Cart:agregar}
#
#
#eliminar_item:
#    pattern:  /removeCart/{id_producto}
#    defaults: { _controller: SetnetArtsenalBundle:Cart:eliminar}
#
#
#clear_item:
#    pattern:  /clearCart
#    defaults: { _controller: SetnetArtsenalBundle:Cart:clear}
#
#
#

#
#
#
#enviar_pedido:
#    pattern:   /enviarPedido
#    defaults:  { _controller: SetnetArtsenalBundle:Cart:despachar }
#
#
#
#get_favorito_btn:
#    pattern:   /getFavorito/{id_producto}
#    defaults:  { _controller: SetnetArtsenalBundle:Producto:getFavoritoBtn }
#
#agregar_favorito:
#    pattern:   /addFavorito/{id_producto}
#    defaults:  { _controller: SetnetArtsenalBundle:Producto:agregarFavorito }
#
#quitar_favorito:
#    pattern:   /removeFavorito/{id_producto}
#    defaults:  { _controller: SetnetArtsenalBundle:Producto:quitarFavorito }
#
#
#
#
#getProductosPorCategoria:
#    pattern:   /byCategoria/{id_categoria}
#    defaults:  { _controller: SetnetArtsenalBundle:Default:getProductosPorCategoria }
#
#
#
#filtrar_subcategoria:
#    pattern:   /filtroSubcategoria/{id_subcategoria}
#    defaults:  { _controller: SetnetArtsenalBundle:Default:filtroSubcategoria }
#
#
#
#get_home:
#    pattern:   /home
#    defaults:  { _controller: SetnetArtsenalBundle:Default:getHome }
#
#
#
#perfil_home:
#    pattern:   /perfilConfig
#    defaults:  { _controller: SetnetArtsenalBundle:Usuario:perfil }
#
#
#
#perfil_index:
#    pattern:   /perfilIndex
#    defaults:  { _controller: SetnetArtsenalBundle:Perfil:index }