app_shop_theme_homepage:
    path:     /
    defaults: { _controller: AppShopThemeBundle:Default:index }

contenido_page:
    path:      /contenido/{contenido}
    defaults:  { _controller: AppShopThemeBundle:Default:contenido }

preguntas_frecuentes_page:
    path:      /preguntas
    defaults:  { _controller: AppShopThemeBundle:Default:preguntas }



ver_categoria_artsenal:
    path:      /categoria/{slug}
    defaults:  { _controller: AppShopThemeBundle:Default:categoria }


productos_filtro:
    path:      /get/productos/{categoria}/{subcategoria}/{precio}/{ciudad}
    defaults:  { _controller: AppShopThemeBundle:Default:filtroProducto }
    options:
        expose: true

ver_cesta_artsenal:
    path:      /cart
    defaults:  { _controller: AppShopThemeBundle:Cart:show }



ver_compras_usuario:
    path:      /compras
    defaults:  { _controller: AppShopThemeBundle:Default:compras }


# tienda


ver_tienda:
    path:      /tienda/ver/{id_tienda}
    defaults:  { _controller: AppShopThemeBundle:Tienda:verTienda }

ver_tiendas_artsenal:
    path:      /tiendas
    defaults:  { _controller: AppShopThemeBundle:Default:tiendas }


tienda_artsenal:
    path:      /ver/tienda
    defaults:  { _controller: AppShopThemeBundle:Default:tienda }



creacion_tienda_artsenal:
    path:      /tienda/creacion/nombre
    defaults:  { _controller: AppShopThemeBundle:Tienda:nombreTienda }

creacion_tienda_producto_artsenal:
    path:      /tienda/creacion/producto
    defaults:  { _controller: AppShopThemeBundle:Tienda:productosTienda }

creacion_tienda_membresia_artsenal:
    path:      /tienda/creacion/membresia
    defaults:  { _controller: AppShopThemeBundle:Tienda:membresiaTienda }

creacion_tienda_finalizar_artsenal:
    path:      /tienda/creacion/finalizar/{tipo_cuenta}
    defaults:  { _controller: AppShopThemeBundle:Tienda:finalizarTienda }

politicas_tienda_artsenal:
    path:      /tienda/creacion/politicas
    defaults:  { _controller: AppShopThemeBundle:Tienda:politicas }

presonaliza_tienda_artsenal:
    path:      /tienda/creacion/personalizar
    defaults:  { _controller: AppShopThemeBundle:Tienda:personalizarTienda }

preview_tienda_artsenal:
    path:      /tienda/preview
    defaults:  { _controller: AppShopThemeBundle:Tienda:preview }


creacion_de_tienda:
    path:      /tienda.creacion
    defaults:  { _controller: AppShopThemeBundle:Tienda:nombreTienda }


producto_tienda:
    path:      /tienda.productos
    defaults:  { _controller: AppShopThemeBundle:Tienda:productosTienda }

personalizar_tienda:
    path:      /tienda.personalizar
    defaults:  { _controller: AppShopThemeBundle:Tienda:personalizarTienda }

politicas_tienda:
    path:      /tienda.politicas
    defaults:  { _controller: AppShopThemeBundle:Tienda:politicas }


preview_tienda:
    path:      /tienda.preview
    defaults:  { _controller: AppShopThemeBundle:Tienda:preview }


ver_tienda_artsenal:
    path:      /tienda.ver/{id_tienda}
    defaults:  { _controller: AppShopThemeBundle:Tienda:ver }



# pago    

descripcion_pago_artsenal:
    path:      /pago/descripcion
    defaults:  { _controller: AppShopThemeBundle:Pago:descripcion }


datos_pago_artsenal:
    path:      /pago/datos/{envio}
    defaults:  { _controller: AppShopThemeBundle:Pago:pago }


pago_realizado_artsenal:
    path:      /pago/finalizar
    defaults:  { _controller: AppShopThemeBundle:Pago:finalizar }




# usuario


perfil_usuario:
    path:      /perfil
    defaults:  { _controller: AppShopThemeBundle:Backend:perfil }


login_artsenal:
    path:      /login_app
    defaults:  { _controller: AppShopThemeBundle:Security:login }


register_artsenal:
    path:      /register_app
    defaults:  { _controller: AppShopThemeBundle:Security:register }

login_check:
    path:      /login_check

salir:
    path:   /logout



# ajax
producto_detalle_mostrar:
    path:      /producto/detalle/{id_producto}
    defaults:  { _controller: AppShopThemeBundle:Default:getProducto }
    options:
        expose: true






# cart

agregar_producto_cart:
    path:      /cart/add/{id_producto}/{cantidad}/{precio}
    defaults:  { _controller: SelnetTiendaOnlineBundle:Cart:agregarProducto }
    options:
        expose: true

remove_producto_cart:
    path:      /cart.remove/{id_producto}
    defaults:  { _controller: SelnetTiendaOnlineBundle:Cart:removeProducto }
    options:
        expose: true

update_producto_cart:
    path:      /cart.update/{id_producto}/{cantidad}/{precio}
    defaults:  { _controller: SelnetTiendaOnlineBundle:Cart:updateProducto }
    options:
        expose: true




# templates



test:
    path:      /test
    defaults:  { _controller: AppShopThemeBundle:Default:test }
