Selnet\TiendaOnlineBundle\Entity\Contenido:
    type: entity
    table: contenido_artsenal
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        categoria:
            type: integer
            nullable: false
        titulo:
            type: string
            length: 150
            fixed: false
            nullable: true


        rawContent:
            type: text
            nullable: false
        contentFormatter:
            type: text
            nullable: false
        contenido:
            type: text
            nullable: true


        publicado:
            type: integer
            length: 1
            fixed: true
            nullable: true
        created_at:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated_at:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update
    lifecycleCallbacks:
        prePersist: [preInsert]
        preUpdate: [preUpdate]
