Selnet\TiendaOnlineBundle\Entity\Subcategoria:
    type: entity
    table: subcategoria
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 45
            fixed: false
            nullable: false
        descripcion:
            type: string
            length: 150
            fixed: false
            nullable: true
        borrado:
            type: integer
            length: 1
            fixed: true
            nullable: true
        created_at:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated_at:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update

        slug:
            type: string
            length: 128
            gedmo:
              slug:
                separator: _
                style: default
                fields:
                  - nombre
    manyToOne:
        categoria:
          targetEntity: Categoria
          inversedBy: subcategorias
          joinColumn:
            name: categoria_id
            referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [preInsertSubcategoria]
        preUpdate: [preUpdateSubcategoria]
