Selnet\TiendaOnlineBundle\Entity\Usuario:
    type:  entity
    table: fos_user
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        nombres:
            type: string
            nullable: false 

        apellidos:
            type: string
            nullable: false

        sexo:
            type: integer
            nullable: false

