Selnet\TiendaOnlineBundle\Entity\Venta:
    type: entity
    table: venta
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        total:
            type: string
            length: 45
            fixed: false
            nullable: false
        usuario:
            type: string
            fixed: false
            nullable: false

        verificada:
            type: integer
            length: 1
            fixed: false
            nullable: false
        envio:
            type: integer
            length: 1
            fixed: false
            nullable: false
        pago:
            type: integer
            length: 1
            fixed: false
            nullable: false

        estado:
            type: integer
            length: 1
            fixed: true
            nullable: false
        created_at:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated_at:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update

    oneToMany:
        detalles:
          targetEntity: DetalleVenta
          mappedBy: venta
          cascade: [ "persist" ]

    lifecycleCallbacks:
        prePersist: [preInsert]
        preUpdate: [preUpdate]
