Setnet\ArtsenalBundle\Entity\ArtCategoria:
    type: entity
    table: art_categoria
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 45
            fixed: false
            nullable: true
        descripcion:
            type: string
            length: 150
            fixed: false
            nullable: true
        borrado:
            type: string
            length: 1
            fixed: true
            nullable: true
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
    lifecycleCallbacks: {  }
