Setnet\ArtsenalBundle\Entity\ArtProductoTag:
    type: entity
    table: art_producto_tag
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
    manyToOne:
        idProducto:
            targetEntity: ArtProducto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_producto:
                    referencedColumnName: id
            orphanRemoval: false
        idTag:
            targetEntity: ArtTags
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tag:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
