Setnet\ArtsenalBundle\Entity\ArtProductoLike:
    type: entity
    table: art_producto_like
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
    manyToOne:
        idProducto:
            targetEntity: ArtProducto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_producto:
                    referencedColumnName: id
            orphanRemoval: false
        idUsuario:
            targetEntity: ArtUsuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
