Setnet\ArtsenalBundle\Entity\ArtSubcategoria:
    type: entity
    table: art_subcategoria
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 45
            fixed: false
            nullable: true
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
        borrado:
            type: string
            length: 1
            fixed: true
            nullable: true
    manyToOne:
        idCategoria:
            targetEntity: ArtCategoria
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_categoria:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
