Setnet\ArtsenalBundle\Entity\ArtTiendaDirFacturacion:
    type: entity
    table: art_tienda_dir_facturacion
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        pais:
            type: string
            length: 30
            fixed: false
            nullable: false
        calle:
            type: string
            length: 100
            fixed: false
            nullable: false
        direccionInfo:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: direccion_info
        ciudad:
            type: string
            length: 30
            fixed: false
            nullable: false
        estado:
            type: string
            length: 30
            fixed: false
            nullable: false
        zip:
            type: string
            length: 10
            fixed: false
            nullable: false
        idTienda:
            type: integer
            unsigned: false
            nullable: false
            column: id_tienda
    lifecycleCallbacks: {  }
