Setnet\ArtsenalBundle\Entity\ArtTiendaPolitica:
    type: entity
    table: art_tienda_politica
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        mensajeBienvenidad:
            type: text
            nullable: true
            column: mensaje_bienvenidad
        pagos:
            type: text
            nullable: true
        envio:
            type: text
            nullable: true
        reembolso:
            type: text
            nullable: true
        informacionAdicional:
            type: text
            nullable: false
            column: informacion_adicional
        vendedor:
            type: text
            nullable: true
    manyToOne:
        idTienda:
            targetEntity: ArtTienda
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tienda:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
