Setnet\ArtsenalBundle\Entity\ArtTienda:
    type: entity
    table: art_tienda
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 80
            fixed: true
            nullable: false
        imagenCabecera:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: imagen_cabecera
        titulo:
            type: string
            length: 50
            fixed: false
            nullable: false
        mensajeCliente:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: mensaje_cliente
        anuncio:
            type: string
            length: 200
            fixed: false
            nullable: false
        estado:
            type: string
            length: 1
            nullable: false
        created:
          type: datetime
          gedmo:
            timestampable:
              on: create
        updated:
          type: datetime
          gedmo:
            timestampable:
              on: update
            
        idUsuario:
            type: integer
            unsigned: false
            nullable: false
            column: id_usuario
            
 

    lifecycleCallbacks: {  }
