Setnet\ArtsenalBundle\Entity\ArtUsuario:
    type: entity
    table: art_usuario
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
        borrado:
            type: string
            length: 1
            fixed: true
            nullable: true
        ultimoLogin:
            type: datetime
            nullable: true
            column: ultimo_login
        configuracionCompleta:
            type: integer
            nullable: true
    oneToOne:
      perfil:
        targetEntity: ArtPerfil
        joinColumn:
          name: perfil_id
          referencedColumnName: id
    oneToOne:
      tienda:
        targetEntity: ArtTienda
        joinColumn:
          name: tienda_id
          referencedColumnName: id
    manyToOne:
      suscripcion:
        targetEntity: ArtSuscripciones
        inversedBy: usuarios
        joinColumn:
          name: suscripcion_id
          referencedColumnName: id



 
    lifecycleCallbacks: {  }
