Setnet\ArtsenalBundle\Entity\ArtUsuarioSeguir:
    type: entity
    table: art_usuario_seguir
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
    manyToOne:
        idTienda:
            targetEntity: ArtTienda
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tienda:
                    referencedColumnName: id
            orphanRemoval: false
        idUsuario:
            targetEntity: ArtPerfil
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
