Setnet\ArtsenalBundle\Entity\Contenido:
    type: entity
    table: contenido
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        categoria:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: imagen_url
        contenido:
            type: text
            nullable: false
        titulo:
            type: string
            length: 250
            fixed: false
            nullable: false
        orden:
            type: integer
            fixed: false
            nullable: false
        estado:
            type: string
            length: 1
            fixed: true
            nullable: false
        created:
          type: datetime
          gedmo:
            timestampable:
              on: create
        updated:
          type: datetime
          gedmo:
            timestampable:
              on: update
    lifecycleCallbacks: {  }
